BarKeep/Controllers/CocktailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BarKeep.Data;
using BarKeep.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.StaticFiles;
using System.IO;
using Amazon.S3;
using Amazon.S3.Transfer;
using Amazon;
using BarKeep.Keys;

namespace BarKeep.Controllers
{
    [Authorize]
    public class CocktailsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IHostingEnvironment _env;

        public CocktailsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager, IHostingEnvironment env)
        {
            _context = context;
            _userManager = userManager;
            _env = env;
        }

        // GET: Cocktails
        public async Task<IActionResult> Index(string searchString, string sortOrder)
        {
            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["AlcoholTypeSortParm"] = String.IsNullOrEmpty(sortOrder) ? "alcoholType_desc" : "";

            var cocktails = _context.Cocktail
                .Include(c => c.AlcoholType)
                .Include(c => c.Glassware)
                .Include(c => c.Ingredients)
                .Include(c => c.User)
                .AsQueryable();

            var ingredients = _context.Ingredient
                .Include(i => i.Cocktail)
                .AsQueryable();

            switch (sortOrder)
            {
                case "name_desc":
                    cocktails = cocktails.OrderBy(c => c.Name);
                    break;
                case "alcoholType_desc":
                    cocktails = cocktails.OrderBy(c => c.AlcoholType.Name);
                    break;
                default:
                    cocktails = cocktails;
                    break;
            }

            if (!String.IsNullOrEmpty(searchString))
            {
                cocktails = cocktails.Where(c => c.Name.Contains(searchString));
                if (cocktails.ToList().Count == 0 || ingredients.Any(i => i.Name.Contains(searchString)))
                {
                    cocktails = ingredients.Where(i => i.Name.Contains(searchString)).Select(i => i.Cocktail).Include(c => c.AlcoholType).Include(c => c.User);
                }
            }


            return View(await cocktails.ToListAsync());
        }

        // GET: My Cocktails
        public async Task<IActionResult> MyCocktails(string sortOrder)
        {
            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["AlcoholTypeSortParm"] = String.IsNullOrEmpty(sortOrder) ? "alcoholType_desc" : "";

            var user = await GetCurrentUserAsync();

            var myCocktails = _context.Cocktail
                .Include(c => c.AlcoholType)
                .Include(c => c.Glassware)
                .Include(c => c.Ingredients)
                .Include(c => c.Instructions)
                .Include(c => c.User)
                .Where(c => c.UserId == user.Id);

            switch (sortOrder)
            {
                case "name_desc":
                    myCocktails = myCocktails.OrderBy(c => c.Name);
                    break;
                case "alcoholType_desc":
                    myCocktails = myCocktails.OrderBy(c => c.AlcoholType.Name);
                    break;
                default:
                    myCocktails = myCocktails;
                    break;
            }

            return View(await myCocktails.ToListAsync());
        }

        //GET: Favorite Cocktails

        public async Task<IActionResult> FavoriteCocktails(string sortOrder)
        {
            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["AlcoholTypeSortParm"] = String.IsNullOrEmpty(sortOrder) ? "alcoholType_desc" : "";

            var user = await GetCurrentUserAsync();

            var favoriteCocktails = await _context.Favorite
                .Where(f => f.UserId == user.Id)
                .Select(cd => cd.Cocktail)
                .Include(c => c.AlcoholType)
                .Include(c => c.Glassware)
                .Include(c => c.User)
                .ToListAsync();

            switch (sortOrder)
            {
                case "name_desc":
                    favoriteCocktails = favoriteCocktails.OrderBy(c => c.Name).ToList();
                    break;
                case "alcoholType_desc":
                    favoriteCocktails = favoriteCocktails.OrderBy(c => c.AlcoholType.Name).ToList();
                    break;
                default:
                    favoriteCocktails = favoriteCocktails;
                    break;
            }

            return View(favoriteCocktails);
        }

        //GET: Questions
        public IActionResult Questions()
        {
            ViewData["AlcoholTypeId"] = new SelectList(_context.AlcoholType, "AlcoholTypeId", "Name");
            ViewData["Descriptor1Id"] = new SelectList(_context.Descriptor, "DescriptorId", "Description");
            ViewData["Descriptor2Id"] = new SelectList(_context.Descriptor, "DescriptorId", "Description");

            return View();
        }

        //GET: Suggested Cocktails
        public async Task<IActionResult> Suggestions(string sortOrder, int alcoholType, int descriptor1, int descriptor2)
        {
            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["AlcoholTypeSortParm"] = String.IsNullOrEmpty(sortOrder) ? "alcoholType_desc" : "";

            var user = await GetCurrentUserAsync();


            var suggestedCocktails = await _context.CocktailDescriptor
                .Where(cd => cd.Cocktail.AlcoholTypeId == alcoholType && (cd.DescriptorId == descriptor1 || cd.DescriptorId == descriptor2))
                .Select(cd => cd.Cocktail)
                .Distinct()
                .Include(c => c.AlcoholType)
                .Include(c => c.Glassware)
                .Include(c => c.User)
                .ToListAsync();

            ViewBag.alcoholType = alcoholType;
            ViewBag.descriptor1 = descriptor1;
            ViewBag.descriptor2 = descriptor2;


            switch (sortOrder)
            {
                case "name_desc":
                    suggestedCocktails = suggestedCocktails.OrderBy(c => c.Name).ToList();
                    break;
                case "alcoholType_desc":
                    suggestedCocktails = suggestedCocktails.OrderBy(c => c.AlcoholType.Name).ToList();
                    break;
                default:
                    suggestedCocktails = suggestedCocktails;
                    break;
            }

            return View(suggestedCocktails);
        }

        // GET: Suggestion/Detail
        public async Task<IActionResult> SuggestionDetails(int? id, int alcoholType, int descriptor1, int descriptor2)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await GetCurrentUserAsync();

            var cocktail = await _context.Cocktail
                .Include(c => c.AlcoholType)
                .Include(c => c.Glassware)
                .Include(c => c.Ingredients)
                .Include(c => c.Instructions)
                .Include(c => c.User)
                .Include(c => c.CocktailDescriptors)
                .ThenInclude(d => d.Descriptor)
                .FirstOrDefaultAsync(m => m.CocktailId == id);

            cocktail.IsFavorite = _context.Favorite
                .Any(f => f.CocktailId == id && f.UserId == user.Id);

            ViewBag.alcoholType = alcoholType;
            ViewBag.descriptor1 = descriptor1;
            ViewBag.descriptor2 = descriptor2;

            if (cocktail == null)
            {
                return NotFound();
            }

            return View(cocktail);
        }

        // GET Random Drink
        public async Task<IActionResult> Random()
        {

            var cocktails = await _context.Cocktail
               .Include(c => c.AlcoholType)
               .Include(c => c.Glassware)
               .Include(c => c.Ingredients)
               .Include(c => c.Instructions)
               .Include(c => c.User)
               .Include(c => c.CocktailDescriptors)
               .ThenInclude(d => d.Descriptor)
               .ToListAsync();

            Random rnd = new Random();
            var cocktail = cocktails[rnd.Next(cocktails.Count)];

            return View(cocktail);
        }

        // Create Favorite
        public async Task<IActionResult> Favorite(int cId)
        {
            var user = await GetCurrentUserAsync();

            var favorite = new Favorite()
            {
                UserId = user.Id,
                CocktailId = cId
            };

            _context.Add(favorite);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Details), new { id = cId });
            //return RedirectToAction(nameof(Index));
        }

        // Remove Favorite
        public async Task<IActionResult> Unfavorite(int cId)
        {
            var user = await GetCurrentUserAsync();

            var favorite = _context.Favorite.FirstOrDefault(f => f.CocktailId == cId && f.UserId == user.Id);

            _context.Remove(favorite);
            await _context.SaveChangesAsync();

            //return RedirectToAction(nameof(Details), new { id = cId });
            return RedirectToAction(nameof(Index));
        }

        // GET: Cocktails/Details/5
        public async Task<IActionResult> Details(int? id)
        {

BarKeep/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BarKeep</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/css/materia.css" />
        <link rel="stylesheet" href="~/lib/font-awesome/css/all.css" />
        <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="~/css/materia.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
        <link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container">
                <i class="fas fa-cocktail fa-2x mr-2"></i>
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BarKeep</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">

                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index"><strong>Home</strong></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cocktails" asp-action="Index"><strong>Cocktails</strong></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cocktails" asp-action="Questions"><strong>Suggestions</strong></a>
                        </li>
                    </ul>
                </div>
                <form class="mx-2 my-auto d-inline w-25" asp-controller="Cocktails" asp-action="Index">
                    <div class="input-group">
                        <input type="text" class="form-control mr-2" placeholder="Search Name or Ingredient..." name="SearchString">
                        <span class="input-group-append">
                            <button class="btn btn-dark" type="submit">
                                <i class="fa fa-search"></i>
                            </button>
                        </span>
                    </div>
                </form>
                <partial name="_LoginPartial" />
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - BarKeep - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
    <script>
        AOS.init({
            duration: 1000
        });
    </script>

    @RenderSection("Scripts", required: false)
</body>
</html>